/*eslint-env es6*/
export const franes = [
    [2,  //0 Tipo de frame 0 -opções, 1 - temporal 2 - texto
    "bg1", // background
    "fg1", // foreground
    "ch0", // charset left side
    1, // Emotion 0 - 7 left side
    "cl1", // clothes left side
    "nll", // charset right side
    0, // Emotion right side
    "nll", // clothes right side
    "nll", // charset center
    0, // emotion center
    "nll", // clothes center
    "Hello, this is the test interface of vnovel 1. I am the -vtsundere I and I am here to help you, not because I like you, Its just my job. Y-you are not a random perv, right? Are you from the dev team? If yes, who are you?", // Frame text
    ["", 
    "",
    "",
    ""], //Options
    [0,
    1,
    0,
    0,
    0,
    0,], // Directives
    0 //Frame Timing
    ], //frame 0 end 
    
    [0,  //1
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "",
    ["Moeller",
    "Jeff",
    "Vnovel Plot",
    "Faya"],
    [0,
    1,
    2,
    3,
    21,
    5,],
    0], //frame 1 end
    
    [2, //2
    "bg1",
    "fg1",
    "ch0",
    3,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "G-game d-director senpai?",
    ["", //Options
    "",
    "",
    ""],
    [1,
    6,
    2,
    2,
    2,
    2,],
    0], //frame 2 end
    
    [2, //3
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Hello fellow tsundero, I trust you will draw me very beautiful.",
    ["", //Options
    "",
    "",
    ""],
    [1,
    3,
    3,
    3,
    3,
    3,],
    0], //frame 3 end
    
    [2, //4
    "bg1",
    "fg1",
    "ch0",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Y-you shold not play this HOI too much, Y-you are not expending much time with me... not like I wanted it.",
    ["", //Options
    "",
    "",
    ""],
    [1,
    10,
    0,
	0,
    0,
    0,],
    0], //frame 4 end
    
    [2, //5
    "bg1",
    "fg1",
    "ch0",
    1,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "*SLAP Y-YOU BAKA HENTAI! You should be working in the game's story, instead coming here to see me!",
    ["", //Options
    "",
    "",
    ""],
    [1,
    5,
    5,
    5,
    5,
    5,],
    0], //frame 5 end
    
    [2, //6
    "bg1",
    "fg1",
    "ch0",
    1,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "*SLAP Y-YOU BAKA HENTAI! AREN'T YOU ASHAMED BY YOUR CODE? I DON'T WANT TO LIVE IN THIS TRASH!",
    ["", //Options
    "",
    "",
    ""],
    [2,
    7,
    6,
    6,
    6,
    6,],
    0], //frame 6 end
    
    [1, //7
    "bg1",
    "fg1",
    "ch0",
    4,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "",
    ["", //Options
    "",
    "",
    ""],
    [8,
    6,
    6,
    6,
    6,
    6,],
    100], //frame 7 end
    
    [2, //8
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "nll",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "I hope you baka is happy with the timed frame",
    ["", //Options
    "",
    "",
    ""],
    [6,
    9,
    8,
    8,
    8,
    8,],
    0], //frame 8 end
    
    [2, //9
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Sup bro",
    ["", //Options
    "",
    "",
    ""],
    [8,
    9,
    9,
    9,
    9,
    9,],
    0], //frame 9 end
        
		
	[2, //10
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Hey listen, theses paradox games will only get more a more expensive, you should stop playing them and expend time with me",
    ["", //Options
    "",
    "",
    ""],
    [4,
    11,
    0,
    0,
    0,
    0,],
    0], //frame 10 end
        	
	
	[0, //11
    "bg1",
    "fg1",
    "ch0",
    0,
    "nl1",
    "nl1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "",
    ["Yeah but playing them is so good", //Options
    "You are right i should stop playing them and start programing you",
    "",
    ""],
    [10,
    10,
    12,
    13,
    0,
    0,],
    0], //frame 11 end
        
		
	[2, //12
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "No, you are only feeding your own adiction",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 12 end
        	
	
	[2, //13
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 13 end
	
	[2, //14
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 14 end
	
	[2, //15
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 15 end
	
	[2, //16
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 16 end
	
	[2, //17
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 17 end
	
	[2, //18
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 18 end
	
	[2, //19
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 19 end
	
	[2, //20
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Yeah this is right, you should spend more time developing me instead of playing games",
    ["", //Options
    "",
    "",
    ""],
    [11,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 20 end
	
	// Começo do Plot VNovel
	
	[2, //21
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You arrive at a village after several days travelling. Your old Lord has died in battle but you didn't had the courage to follow his path and has walked theses lands in search of any kind of job",
    ["", //Options
    "",
    "",
    ""],
    [1,
    22,
    1,
    1,
    1,
    1,],
    0], //frame 21 end
	
	[2, //22
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:Finally I arrived somewhere, theses days travelling have been so hard with the war going on all sides, but atleast, i have some semblance of hope in this life",
    ["", //Options
    "",
    "",
    ""],
    [21,
    23,
    1,
    1,
    1,
    1,],
    0], //frame 22 end
	
	[2, //23
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "As you approach the village you see signs of an attack. You would ignore such village in a any other day but as desperation hits you, you approach it in hope that you can find some food and a roof over your head",
    ["", //Options
    "",
    "",
    ""],
    [22,
    24,
    1,
    1,
    1,
    1,],
    0], //frame 23 end
	
	[2, //24
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Hello Citizen, what happened here? Have your village been raided by bandits?",
    ["", //Options
    "",
    "",
    ""],
    [23,
    25,
    1,
    1,
    1,
    1,],
    0], //frame 24 end
	
	// (Comentário:Toda a vez que vejo o frame 24 eu rio porque não tive idéia melhor de dialogo mas ao mesmo tempo esse início é comico)
	
	[2, //25
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager is surprised by your sudden arrival, but after a second he recovers and answer in some bad mood",
    ["", //Options
    "",
    "",
    ""],
    [24,
    26,
    1,
    1,
    1,
    1,],
    0], //frame 25 end
	
	[2, //26
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager:Yeah some bandits attack us not long ago and killed some of the people here. Now if you don't have anything better to do could you stop wasting my time?",
    ["", //Options
    "",
    "",
    ""],
    [25,
    27,
    1,
    1,
    1,
    1,],
    0], //frame 26 end
	
	[2, //27
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Well to not waste more of your time then i have a proposal. I'm searching for a job and as you can see i'm a mercenary. Do you guys nhave anything for me to do or help here?",
    ["", //Options
    "",
    "",
    ""],
    [26,
    28,
    1,
    1,
    1,
    1,],
    0], //frame 27 end
	
	[2, //28
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager looks at you suspecting of you, but he says",
    ["", //Options
    "",
    "",
    ""],
    [27,
    29,
    1,
    1,
    1,
    1,],
    0], //frame 28 end
	
	[2, //29
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager: If you wanna talk about any jobs talk to our elder, he is over there",
    ["", //Options
    "",
    "",
    ""],
    [28,
    30,
    1,
    1,
    1,
    1,],
    0], //frame 29 end
	
	[2, //30
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You go to the person that the guy pointed to you and explain your situation",
    ["", //Options
    "",
    "",
    ""],
    [29,
    31,
    1,
    1,
    1,
    1,],
    0], //frame 30 end
	
	[2, //31
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:... So this is my history, like I said i just want a job, i can help with anything here if you let me stay in one of the houses and give me some food",
    ["", //Options
    "",
    "",
    ""],
    [30,
    32,
    1,
    1,
    1,
    1,],
    0], //frame 31 end
	
	[2, //32
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder:Ok, but first i need to talk to the others to see if they agree with it",
    ["", //Options
    "",
    "",
    ""],
    [31,
    33,
    1,
    1,
    1,
    1,],
    0], //frame 32 end
	
	[2, //33
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Some time passes, but the eldar returns and says",
    ["", //Options
    "",
    "",
    ""],
    [32,
    34,
    1,
    1,
    1,
    1,],
    0], //frame 33 end
	
	[2, //34
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder; Your arrival here is strange, I can't deny that, however we need any help we can get. We will give you some food and a roof, but today go sleep, you appear tired from all your travel",
    ["", //Options
    "",
    "",
    ""],
    [33,
    35,
    1,
    1,
    1,
    1,],
    0], //frame 34 end
	
	[2, //35
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Thanks, you can believe me I will help you as I can",
    ["", //Options
    "",
    "",
    ""],
    [34,
    36,
    1,
    1,
    1,
    1,],
    0], //frame 35 end
	
	[2, //36
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder: We will see that",
    ["", //Options
    "",
    "",
    ""],
    [35,
    37,
    1,
    1,
    1,
    1,],
    0], //frame 36 end
	
	// Fim da Cena 1
	
	
	[2, //37
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You spent two weeks helping rebuild the village. You helped rebuilding some houses and securing it from badits raids. When you began your work the villagers suspected that you worked with the bandits but after some days theses rumors stopped after you gain some respect from them. After a hunting you noticed some new people in the village, you aproach one of the villagers and ask ",
    ["", //Options
    "",
    "",
    ""],
    [36,
    38,
    1,
    1,
    1,
    1,],
    0], //frame 37 end
	
	[2, //38
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:Hey what is happening? Who are they?",
    ["", //Options
    "",
    "",
    ""],
    [37,
    39,
    1,
    1,
    1,
    1,],
    0], //frame 38 end
	
	[2, //39
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager: It appears that they are soldiers from the actual Lord, they stopped here to rest while they go to the next battle",
    ["", //Options
    "",
    "",
    ""],
    [38,
    40,
    1,
    1,
    1,
    1,],
    0], //frame 39 end
	
	[2, //40
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: I don't know how the new Lord is let us not make anything that can make them nervous ",
    ["", //Options
    "",
    "",
    ""],
    [39,
    41,
    1,
    1,
    1,
    1,],
    0], //frame 40 end
	
	
	[2, //41
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You leave before the villager replies to you. You keep an eye out for the soldiers as you were their enemy one time trying to no stay in their sight, but while you maintain your vigilance over them you notice something unusual. You notice that their commander is a beatiful girl and that she maintain the order easily.",
    ["", //Options
    "",
    "",
    ""],
    [40,
    42,
    1,
    1,
    1,
    1,],
    0], //frame 41 end
	
	[2, //42
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager:Yeah some bandits attack us not long ago and killed some of the people here. Now if you don't have anything better to do could you stop wasting my time?",
    ["", //Options
    "",
    "",
    ""],
    [25,
    27,
    1,
    1,
    1,
    1,],
    0], //frame 42 end
	
	[2, //43
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Well to not waste more of your time then i have a proposal. I'm searching for a job and as you can see i'm a mercenary. Do you guys nhave anything for me to do or help here?",
    ["", //Options
    "",
    "",
    ""],
    [26,
    28,
    1,
    1,
    1,
    1,],
    0], //frame 43 end
	
	[2, //44
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager looks at you suspecting of you, but he says",
    ["", //Options
    "",
    "",
    ""],
    [27,
    29,
    1,
    1,
    1,
    1,],
    0], //frame 44 end
	
	[2, //45
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager: If you wanna talk about any jobs talk to our elder, he is over there",
    ["", //Options
    "",
    "",
    ""],
    [28,
    30,
    1,
    1,
    1,
    1,],
    0], //frame 45 end
	
	[2, //46
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You go to the person that the guy pointed to you and explain your situation",
    ["", //Options
    "",
    "",
    ""],
    [29,
    31,
    1,
    1,
    1,
    1,],
    0], //frame 46 end
	
	[2, //47
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:... So this is my history, like I said i just want a job, i can help with anything here if you let me stay in one of the houses and give me some food",
    ["", //Options
    "",
    "",
    ""],
    [30,
    32,
    1,
    1,
    1,
    1,],
    0], //frame 47 end
	
	[2, //48
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder:Ok, but first i need to talk to the others to see if they agree with it",
    ["", //Options
    "",
    "",
    ""],
    [31,
    33,
    1,
    1,
    1,
    1,],
    0], //frame 48 end
	
	[2, //49
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Some time passes, but the eldar returns and says",
    ["", //Options
    "",
    "",
    ""],
    [32,
    34,
    1,
    1,
    1,
    1,],
    0], //frame 49 end
	
	[2, //50
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder; Your arrival here is strange, I can't deny that, however we need any help we can get. We will give you some food and a roof, but today go sleep, you appear tired from all your travel",
    ["", //Options
    "",
    "",
    ""],
    [33,
    35,
    1,
    1,
    1,
    1,],
    0], //frame 50 end
	
	[2, //51
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Thanks, you can believe me I will help you as I can",
    ["", //Options
    "",
    "",
    ""],
    [34,
    36,
    1,
    1,
    1,
    1,],
    0], //frame 51 end
	
	[2, //52
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder: We will see that",
    ["", //Options
    "",
    "",
    ""],
    [35,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 52 end
	
	//Fim da Cena 2
	[2, //53
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You arrive at a village after several days travelling. Your old Lord has died in battle but you didn't had the courage to follow his path and has walked theses lands in search of any kind of job",
    ["", //Options
    "",
    "",
    ""],
    [1,
    22,
    1,
    1,
    1,
    1,],
    0], //frame 53 end
	
	[2, //54
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:Finally I arrived somewhere, theses days travelling have been so hard with the war going on all sides, but atleast, i have some semblance of hope in this life",
    ["", //Options
    "",
    "",
    ""],
    [21,
    23,
    1,
    1,
    1,
    1,],
    0], //frame 54 end
	
	[2, //55
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "As you approach the village you see signs of an attack. You would ignore such village in a any other day but as desperation hits you, you approach it in hope that you can find some food and a roof over your head",
    ["", //Options
    "",
    "",
    ""],
    [22,
    24,
    1,
    1,
    1,
    1,],
    0], //frame 55 end
	
	[2, //56
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Hello Citizen, what happened here? Have your village been raided by bandits?",
    ["", //Options
    "",
    "",
    ""],
    [23,
    25,
    1,
    1,
    1,
    1,],
    0], //frame 56 end
	
	
	[2, //57
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager is surprised by your sudden arrival, but after a second he recovers and answer in some bad mood",
    ["", //Options
    "",
    "",
    ""],
    [24,
    26,
    1,
    1,
    1,
    1,],
    0], //frame 57 end
	
	[2, //58
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager:Yeah some bandits attack us not long ago and killed some of the people here. Now if you don't have anything better to do could you stop wasting my time?",
    ["", //Options
    "",
    "",
    ""],
    [25,
    27,
    1,
    1,
    1,
    1,],
    0], //frame 58 end
	
	[2, //59
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Well to not waste more of your time then i have a proposal. I'm searching for a job and as you can see i'm a mercenary. Do you guys nhave anything for me to do or help here?",
    ["", //Options
    "",
    "",
    ""],
    [26,
    28,
    1,
    1,
    1,
    1,],
    0], //frame 59 end
	
	[2, //60
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager looks at you suspecting of you, but he says",
    ["", //Options
    "",
    "",
    ""],
    [27,
    29,
    1,
    1,
    1,
    1,],
    0], //frame 60 end
	
	[2, //61
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager: If you wanna talk about any jobs talk to our elder, he is over there",
    ["", //Options
    "",
    "",
    ""],
    [28,
    30,
    1,
    1,
    1,
    1,],
    0], //frame 61 end
	
	[2, //62
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You go to the person that the guy pointed to you and explain your situation",
    ["", //Options
    "",
    "",
    ""],
    [29,
    31,
    1,
    1,
    1,
    1,],
    0], //frame 62 end
	
	[2, //63
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:... So this is my history, like I said i just want a job, i can help with anything here if you let me stay in one of the houses and give me some food",
    ["", //Options
    "",
    "",
    ""],
    [30,
    32,
    1,
    1,
    1,
    1,],
    0], //frame 63 end
	
	[2, //64
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder:Ok, but first i need to talk to the others to see if they agree with it",
    ["", //Options
    "",
    "",
    ""],
    [31,
    33,
    1,
    1,
    1,
    1,],
    0], //frame 64 end
	
	[2, //65
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Some time passes, but the eldar returns and says",
    ["", //Options
    "",
    "",
    ""],
    [32,
    34,
    1,
    1,
    1,
    1,],
    0], //frame 65 end
	
	[2, //66
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder; Your arrival here is strange, I can't deny that, however we need any help we can get. We will give you some food and a roof, but today go sleep, you appear tired from all your travel",
    ["", //Options
    "",
    "",
    ""],
    [33,
    35,
    1,
    1,
    1,
    1,],
    0], //frame 66 end
	
	[2, //67
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Thanks, you can believe me I will help you as I can",
    ["", //Options
    "",
    "",
    ""],
    [34,
    36,
    1,
    1,
    1,
    1,],
    0], //frame 67 end
	
	[2, //68
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder: We will see that",
    ["", //Options
    "",
    "",
    ""],
    [35,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 68 end
	
	//Fim da Cena 3
	
	[2, //69
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You arrive at a village after several days travelling. Your old Lord has died in battle but you didn't had the courage to follow his path and has walked theses lands in search of any kind of job",
    ["", //Options
    "",
    "",
    ""],
    [1,
    22,
    1,
    1,
    1,
    1,],
    0], //frame 69 end
	
	[2, //70
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:Finally I arrived somewhere, theses days travelling have been so hard with the war going on all sides, but atleast, i have some semblance of hope in this life",
    ["", //Options
    "",
    "",
    ""],
    [21,
    23,
    1,
    1,
    1,
    1,],
    0], //frame 70 end
	
	[2, //71
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "As you approach the village you see signs of an attack. You would ignore such village in a any other day but as desperation hits you, you approach it in hope that you can find some food and a roof over your head",
    ["", //Options
    "",
    "",
    ""],
    [22,
    24,
    1,
    1,
    1,
    1,],
    0], //frame 71 end
	
	[2, //72
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Hello Citizen, what happened here? Have your village been raided by bandits?",
    ["", //Options
    "",
    "",
    ""],
    [23,
    25,
    1,
    1,
    1,
    1,],
    0], //frame 72 end
	
	
	[2, //73
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager is surprised by your sudden arrival, but after a second he recovers and answer in some bad mood",
    ["", //Options
    "",
    "",
    ""],
    [24,
    26,
    1,
    1,
    1,
    1,],
    0], //frame 73 end
	
	[2, //74
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager:Yeah some bandits attack us not long ago and killed some of the people here. Now if you don't have anything better to do could you stop wasting my time?",
    ["", //Options
    "",
    "",
    ""],
    [25,
    27,
    1,
    1,
    1,
    1,],
    0], //frame 74 end
	
	[2, //75
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Well to not waste more of your time then i have a proposal. I'm searching for a job and as you can see i'm a mercenary. Do you guys nhave anything for me to do or help here?",
    ["", //Options
    "",
    "",
    ""],
    [26,
    28,
    1,
    1,
    1,
    1,],
    0], //frame 75 end
	
	[2, //76
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager looks at you suspecting of you, but he says",
    ["", //Options
    "",
    "",
    ""],
    [27,
    29,
    1,
    1,
    1,
    1,],
    0], //frame 76 end
	
	[2, //77
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager: If you wanna talk about any jobs talk to our elder, he is over there",
    ["", //Options
    "",
    "",
    ""],
    [28,
    30,
    1,
    1,
    1,
    1,],
    0], //frame 77 end
	
	[2, //78
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You go to the person that the guy pointed to you and explain your situation",
    ["", //Options
    "",
    "",
    ""],
    [29,
    31,
    1,
    1,
    1,
    1,],
    0], //frame 78 end
	
	[2, //79
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:... So this is my history, like I said i just want a job, i can help with anything here if you let me stay in one of the houses and give me some food",
    ["", //Options
    "",
    "",
    ""],
    [30,
    32,
    1,
    1,
    1,
    1,],
    0], //frame 79 end
	
	[2, //80
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder:Ok, but first i need to talk to the others to see if they agree with it",
    ["", //Options
    "",
    "",
    ""],
    [31,
    33,
    1,
    1,
    1,
    1,],
    0], //frame 80 end
	
	[2, //81
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Some time passes, but the eldar returns and says",
    ["", //Options
    "",
    "",
    ""],
    [32,
    34,
    1,
    1,
    1,
    1,],
    0], //frame 81 end
	
	[2, //82
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder; Your arrival here is strange, I can't deny that, however we need any help we can get. We will give you some food and a roof, but today go sleep, you appear tired from all your travel",
    ["", //Options
    "",
    "",
    ""],
    [33,
    35,
    1,
    1,
    1,
    1,],
    0], //frame 82 end
	
	[2, //83
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Thanks, you can believe me I will help you as I can",
    ["", //Options
    "",
    "",
    ""],
    [34,
    36,
    1,
    1,
    1,
    1,],
    0], //frame 83 end
	
	[2, //84
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder: We will see that",
    ["", //Options
    "",
    "",
    ""],
    [35,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 84 end
	
	//Fim da Cena 4
	
	[2, //85
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You arrive at a village after several days travelling. Your old Lord has died in battle but you didn't had the courage to follow his path and has walked theses lands in search of any kind of job",
    ["", //Options
    "",
    "",
    ""],
    [1,
    22,
    1,
    1,
    1,
    1,],
    0], //frame 85 end
	
	[2, //86
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:Finally I arrived somewhere, theses days travelling have been so hard with the war going on all sides, but atleast, i have some semblance of hope in this life",
    ["", //Options
    "",
    "",
    ""],
    [21,
    23,
    1,
    1,
    1,
    1,],
    0], //frame 86 end
	
	[2, //87
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "As you approach the village you see signs of an attack. You would ignore such village in a any other day but as desperation hits you, you approach it in hope that you can find some food and a roof over your head",
    ["", //Options
    "",
    "",
    ""],
    [22,
    24,
    1,
    1,
    1,
    1,],
    0], //frame 87 end
	
	[2, //88
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Hello Citizen, what happened here? Have your village been raided by bandits?",
    ["", //Options
    "",
    "",
    ""],
    [23,
    25,
    1,
    1,
    1,
    1,],
    0], //frame 88 end
		
	[2, //89
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager is surprised by your sudden arrival, but after a second he recovers and answer in some bad mood",
    ["", //Options
    "",
    "",
    ""],
    [24,
    26,
    1,
    1,
    1,
    1,],
    0], //frame 89 end
	
	[2, //90
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager:Yeah some bandits attack us not long ago and killed some of the people here. Now if you don't have anything better to do could you stop wasting my time?",
    ["", //Options
    "",
    "",
    ""],
    [25,
    27,
    1,
    1,
    1,
    1,],
    0], //frame 90 end
	
	[2, //91
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Well to not waste more of your time then i have a proposal. I'm searching for a job and as you can see i'm a mercenary. Do you guys nhave anything for me to do or help here?",
    ["", //Options
    "",
    "",
    ""],
    [26,
    28,
    1,
    1,
    1,
    1,],
    0], //frame 91 end
	
	[2, //92
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "The villager looks at you suspecting of you, but he says",
    ["", //Options
    "",
    "",
    ""],
    [27,
    29,
    1,
    1,
    1,
    1,],
    0], //frame 92 end
	
	[2, //93
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Villager: If you wanna talk about any jobs talk to our elder, he is over there",
    ["", //Options
    "",
    "",
    ""],
    [28,
    30,
    1,
    1,
    1,
    1,],
    0], //frame 93 end
	
	[2, //94
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "You go to the person that the guy pointed to you and explain your situation",
    ["", //Options
    "",
    "",
    ""],
    [29,
    31,
    1,
    1,
    1,
    1,],
    0], //frame 94 end
	
	[2, //95
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist:... So this is my history, like I said i just want a job, i can help with anything here if you let me stay in one of the houses and give me some food",
    ["", //Options
    "",
    "",
    ""],
    [30,
    32,
    1,
    1,
    1,
    1,],
    0], //frame 95 end
	
	[2, //96
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder:Ok, but first i need to talk to the others to see if they agree with it",
    ["", //Options
    "",
    "",
    ""],
    [31,
    33,
    1,
    1,
    1,
    1,],
    0], //frame 96 end
	
	[2, //97
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Some time passes, but the eldar returns and says",
    ["", //Options
    "",
    "",
    ""],
    [32,
    34,
    1,
    1,
    1,
    1,],
    0], //frame 97 end
	
	[2, //98
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder; Your arrival here is strange, I can't deny that, however we need any help we can get. We will give you some food and a roof, but today go sleep, you appear tired from all your travel",
    ["", //Options
    "",
    "",
    ""],
    [33,
    35,
    1,
    1,
    1,
    1,],
    0], //frame 98 end
	
	[2, //99
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Protagonist: Thanks, you can believe me I will help you as I can",
    ["", //Options
    "",
    "",
    ""],
    [34,
    36,
    1,
    1,
    1,
    1,],
    0], //frame 99 end
	
	[2, //100
    "bg1",
    "fg1",
    "ch0",
    0,
    "cl1",
    "ch1",
    0,
    "nll",
    "nll",
    0,
    "nll",
    "Elder: We will see that",
    ["", //Options
    "",
    "",
    ""],
    [35,
    1,
    1,
    1,
    1,
    1,],
    0], //frame 100 end
	//Fim da Cena 5
        ]	
	
		